sudo: true
dist: trusty
jdk:
    - oraclejdk8
language: java

before_install:
    - psql -U postgres -c "create extension postgis"
    - psql -c 'create user dataarc CREATEDB;' -U postgres
    - psql -c 'create database dataarc' -U dataarc -d template1
    - export DISPLAY=:99.0
    - export MAVEN_SKIP_RC=true
    - export MAVEN_OPTS="-Xms256m -Xmx2048m  -XX:MaxPermSize=512m"
    - sh -e /etc/init.d/xvfb start
    - jdk_switcher use oraclejdk8
    - env
addons:
  firefox: "latest"
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $TRAVIS_BUILD_DIR/node_modules
install:
    - travis_wait 120 mvn -q install -N -DskipTests
script: 
    - travis_wait 200 mvn -q compile verify
services:
    - postgresql
    - mongodb
#env: DB=postgres