sudo: true
dist: trusty
jdk:
    - oraclejdk8
language: java

before_install:
    - psql -c 'create user dataarc CREATEDB;' -U postgres
    - psql -c 'create database dataarc' -U dataarc -d template1
    - psql -U postgres -c "CREATE EXTENSION postgis; CREATE EXTENSION postgis_topology" dataarc
    - export DISPLAY=:99.0
    - export MAVEN_SKIP_RC=true
    - export MAVEN_OPTS="-Xms256m -Xmx2048m  -XX:MaxPermSize=512m"
    - sh -e /etc/init.d/xvfb start
    - jdk_switcher use oraclejdk8
    - env
    - cp src/test/resources/dataarc.properties src/main/resources/dataarc.properties
addons:
  hosts:
    - db
    - localhost
    - mongo
    - web
  firefox: "latest"
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $TRAVIS_BUILD_DIR/node_modules
install:
    - mvn -q install -N -DskipTests
    - mvn clean compile -PloadTestData
script: 
    - travis_wait 200 mvn -q compile verify
services:
    - postgresql
    - mongodb
#env: DB=postgres