version: '3'
services:
  db:
    image: postgres:9.6
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./docker/postgres:/var/lib/postgresql/data
    # ports:
    #     - "5432:5432"
    environment:
        POSTGRES_PASSWORD: dataarc
        POSTGRES_USERNAME: dataarc
  mongo:
    image: mongo:3.4
    volumes:
      - ./docker/mongo:/data/db
    # ports:
    #   - "27017:27017"
  web:
    build: .
    image: dataarc/web
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "8280:8280"
    links:
      - db
      - mongo
      
## docker-compose build --pull
## docker-compose up