version: '3'
services:
  db:
    image: postgres:9.6
    restart: always
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: dataarc
        POSTGRES_USERNAME: dataarc
  cron:
    build: 
      context: .
      dockerfile: CronDockerfile 
    hostname: cron
    restart: always
    volumes:
      - ./docker/backups:/backups
      - /etc/localtime:/etc/localtime:ro
    tty: true
    entrypoint: ""
    user: root
    command: crond -f -d 8
    links:
      - db:db
      - mongo:mongo
    environment:
        POSTGRES_PASSWORD: dataarc
        POSTGRES_USERNAME: dataarc
        POSTGRES_HOST: db
  mongo:
    image: mongo:3.4
    restart: always
    volumes:
      - ./docker/mongo:/data/db
    # ports:
    #   - "27017:27017"
  web:
    build: .
    restart: always
    image: dataarc/web
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "8280:8280"
    links:
      - db
      - mongo
      
## docker-compose build --pull
## docker-compose up