version: '3'
services:
  db:
    image: postgres:9.6
    restart: always
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: dataarc
        POSTGRES_USERNAME: dataarc
  dbbackups:
    image: kartoza/pg-backup:9.4
    hostname: pg-backups
    restart: always
    volumes:
      - ./docker/backups:/backups
    links:
      - db:db
    environment:
      - DUMPPREFIX=dataarc
      # These are all defaults anyway, but setting explicitly in
      # case we ever want to ever use different credentials
      - POSTGRES_USER=dataarc
      - POSTGRES_PASS=dataarc
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - POSTGRES_DBNAME=dataarc
  mongo:
    image: mongo:3.4
    restart: always
    volumes:
      - ./docker/mongo:/data/db
    # ports:
    #   - "27017:27017"
  web:
    build: .
    restart: always
    image: dataarc/web
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "8280:8280"
    links:
      - db
      - mongo
      
## docker-compose build --pull
## docker-compose up