//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.18 at 09:17:02 AM MST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.topicmaps.org/xtm/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package topicmap.v2_0;
