//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.18 at 09:17:02 AM MST 
//

package topicmap.v2_0;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.topicmaps.org/xtm/}itemIdentity" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.topicmaps.org/xtm/}type"/>
 *         &lt;element ref="{http://www.topicmaps.org/xtm/}topicRef"/>
 *       &lt;/sequence>
 *       &lt;attribute name="reifier" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "itemIdentity",
        "type",
        "topicRef"
})
@XmlRootElement(name = "role")
public class Role {

    protected List<ItemIdentity> itemIdentity;
    @XmlElement(required = true)
    protected Type type;
    @XmlElement(required = true)
    protected TopicRef topicRef;
    @XmlAttribute(name = "reifier")
    @XmlSchemaType(name = "anyURI")
    protected String reifier;

    /**
     * Gets the value of the itemIdentity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemIdentity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getItemIdentity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemIdentity }
     * 
     * 
     */
    public List<ItemIdentity> getItemIdentity() {
        if (itemIdentity == null) {
            itemIdentity = new ArrayList<ItemIdentity>();
        }
        return this.itemIdentity;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *         possible object is
     *         {@link Type }
     * 
     */
    public Type getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *            allowed object is
     *            {@link Type }
     * 
     */
    public void setType(Type value) {
        this.type = value;
    }

    /**
     * Gets the value of the topicRef property.
     * 
     * @return
     *         possible object is
     *         {@link TopicRef }
     * 
     */
    public TopicRef getTopicRef() {
        return topicRef;
    }

    /**
     * Sets the value of the topicRef property.
     * 
     * @param value
     *            allowed object is
     *            {@link TopicRef }
     * 
     */
    public void setTopicRef(TopicRef value) {
        this.topicRef = value;
    }

    /**
     * Gets the value of the reifier property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getReifier() {
        return reifier;
    }

    /**
     * Sets the value of the reifier property.
     * 
     * @param value
     *            allowed object is
     *            {@link String }
     * 
     */
    public void setReifier(String value) {
        this.reifier = value;
    }

}
